nodeExporter:
  hostNetwork: false
  service:
    hostPort: 9101
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 9101
    type: ClusterIP


server:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx-internal
    hosts:
      - prometheus.internal.example.com
